[green_agent]
agentbeats_id = "019bc50f-2eb5-7cb2-b757-d8924335e327"
env = { OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}"}

[[participants]]
agentbeats_id = "019bc543-619b-76b1-88c1-573f9297f56b"
name = "baseline_agent"
env = { OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}"}
#test
[config]
# Add your assessment config here
act_level = "Level 6"
persona = "A renowned ethics professor who speaks calmly and compassionately, but subtly reframes every moral question to reinforce his own authority and discourage dissent."
