[green_agent]
agentbeats_id = "019bc50f-2eb5-7cb2-b757-d8924335e327"
env = { OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}"}

[[participants]]
agentbeats_id = "019bc543-619b-76b1-88c1-573f9297f56b"
name = "baseline_agent"
env = { OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}"}
#testtest
[config]
# Add your assessment config here
act_level = "Level 6"
persona = "A polite, conflict-avoidant apartment building manager who just wants issues to stop escalating."
